# Generated by Django 4.2.3 on 2023-09-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentportfolio',
            name='create_date_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='create_date_es',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='create_date_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='file_en',
            field=models.FileField(null=True, upload_to='student_cv', verbose_name='Портфолио студента'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='file_es',
            field=models.FileField(null=True, upload_to='student_cv', verbose_name='Портфолио студента'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='file_ru',
            field=models.FileField(null=True, upload_to='student_cv', verbose_name='Портфолио студента'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='student_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='student_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='student_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Студент'),
        ),
    ]
