# Generated by Django 4.2.3 on 2023-08-28 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('project_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='Стоимость')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='оценка')),
            ],
            options={
                'verbose_name': 'Задача тесовое',
                'verbose_name_plural': 'Задача тестовое',
            },
        ),
        migrations.AlterModelOptions(
            name='answergroup',
            options={'verbose_name': 'Ответ группы', 'verbose_name_plural': 'Ответ группы'},
        ),
        migrations.AlterModelOptions(
            name='answersstudent',
            options={'verbose_name': 'Ответ студента', 'verbose_name_plural': 'Ответ студента'},
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='project_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='taskstudent',
            name='project_cost',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Стоимость'),
        ),
        migrations.CreateModel(
            name='AnswerTestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='file_a', verbose_name='Ответ файлом')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ответ ссылкой')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.testtask', verbose_name='Ответ группы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ группы',
                'verbose_name_plural': 'Ответ группы',
            },
        ),
    ]
