# Generated by Django 4.2.3 on 2023-07-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('mobile_phone', models.CharField(max_length=15, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('tg_nickname', models.CharField(max_length=50, verbose_name='Ник в Телеграм')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('university', models.CharField(max_length=255, verbose_name='ВУЗ')),
                ('course', models.PositiveIntegerField(verbose_name='Курс')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('status', models.CharField(choices=[('previous_flow', 'Прошлый поток'), ('subscribed_to_chatbot', 'Подписан на чат-бот'), ('lead', 'Лид'), ('in_progress', 'В работе у менеджера'), ('rejected', 'Отказ'), ('awaiting_payment', 'Ожидает оплаты'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен'), ('graduate', 'Выпускник'), ('working_group', 'Рабочая группа'), ('dropout', 'Выбыл')], max_length=30, verbose_name='Статус')),
                ('hours_per_week', models.PositiveIntegerField(verbose_name='Сколько часов готовы уделять в неделю')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
