# Generated by Django 4.2.3 on 2023-08-28 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_testtask_alter_answergroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answertesttask',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AddField(
            model_name='answergroup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answersstudent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answersstudent',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taskstudent', verbose_name='Ответ на задачу'),
        ),
        migrations.AlterField(
            model_name='answertesttask',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.testtask', verbose_name='Ответ по задаче'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tg_nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ник в Телеграм'),
        ),
    ]
