# Generated by Django 4.2.3 on 2023-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_studentportfolio_create_date_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Телеграм ID User'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_status',
            field=models.CharField(choices=[('Registration for Free Subscription', 'Регистрация на бесплатную подписку'), ('Completed Free Subscription', 'Завершена бесплатная подписка'), ('Paid Subscription Participant', 'Участник платной подписки'), ('Course Participant', 'Участник курса'), ('Dropout', 'Выбыл'), ('Completed Education', 'Завершил обучение')], max_length=50, verbose_name='Статус обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_status_en',
            field=models.CharField(choices=[('Registration for Free Subscription', 'Регистрация на бесплатную подписку'), ('Completed Free Subscription', 'Завершена бесплатная подписка'), ('Paid Subscription Participant', 'Участник платной подписки'), ('Course Participant', 'Участник курса'), ('Dropout', 'Выбыл'), ('Completed Education', 'Завершил обучение')], max_length=50, null=True, verbose_name='Статус обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_status_es',
            field=models.CharField(choices=[('Registration for Free Subscription', 'Регистрация на бесплатную подписку'), ('Completed Free Subscription', 'Завершена бесплатная подписка'), ('Paid Subscription Participant', 'Участник платной подписки'), ('Course Participant', 'Участник курса'), ('Dropout', 'Выбыл'), ('Completed Education', 'Завершил обучение')], max_length=50, null=True, verbose_name='Статус обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_status_ru',
            field=models.CharField(choices=[('Registration for Free Subscription', 'Регистрация на бесплатную подписку'), ('Completed Free Subscription', 'Завершена бесплатная подписка'), ('Paid Subscription Participant', 'Участник платной подписки'), ('Course Participant', 'Участник курса'), ('Dropout', 'Выбыл'), ('Completed Education', 'Завершил обучение')], max_length=50, null=True, verbose_name='Статус обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='manager_status',
            field=models.CharField(choices=[('Manager Lead', 'Лид менеджера'), ('In Progress with Manager', 'В работе у менеджера'), ('Rejected', 'Отказ'), ('Awaiting Payment', 'Ожидает оплаты'), ('Partially Paid', 'Частично оплачен'), ('Paid', 'Оплачен')], max_length=50, verbose_name='Статус менеджера'),
        ),
        migrations.AlterField(
            model_name='student',
            name='manager_status_en',
            field=models.CharField(choices=[('Manager Lead', 'Лид менеджера'), ('In Progress with Manager', 'В работе у менеджера'), ('Rejected', 'Отказ'), ('Awaiting Payment', 'Ожидает оплаты'), ('Partially Paid', 'Частично оплачен'), ('Paid', 'Оплачен')], max_length=50, null=True, verbose_name='Статус менеджера'),
        ),
        migrations.AlterField(
            model_name='student',
            name='manager_status_es',
            field=models.CharField(choices=[('Manager Lead', 'Лид менеджера'), ('In Progress with Manager', 'В работе у менеджера'), ('Rejected', 'Отказ'), ('Awaiting Payment', 'Ожидает оплаты'), ('Partially Paid', 'Частично оплачен'), ('Paid', 'Оплачен')], max_length=50, null=True, verbose_name='Статус менеджера'),
        ),
        migrations.AlterField(
            model_name='student',
            name='manager_status_ru',
            field=models.CharField(choices=[('Manager Lead', 'Лид менеджера'), ('In Progress with Manager', 'В работе у менеджера'), ('Rejected', 'Отказ'), ('Awaiting Payment', 'Ожидает оплаты'), ('Partially Paid', 'Частично оплачен'), ('Paid', 'Оплачен')], max_length=50, null=True, verbose_name='Статус менеджера'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_phone',
            field=models.CharField(max_length=25, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_phone_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_phone_es',
            field=models.CharField(max_length=25, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_phone_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='Мобильный телефон'),
        ),
    ]
