# Generated by Django 4.2.3 on 2023-08-03 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_group_students', to='account.student')),
                ('students', models.ManyToManyField(related_name='group_students', to='account.student')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('intricacy', models.CharField(max_length=250, verbose_name='Сложность')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('grade', models.CharField(max_length=250, verbose_name='Оценка')),
                ('group', models.ManyToManyField(to='account.groupstudent', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проект',
            },
        ),
        migrations.CreateModel(
            name='StudentCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_cv', verbose_name='Резюме студента')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_cv', verbose_name='Портфолио студента')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('project_cost', models.CharField(max_length=120, verbose_name='Стоимость')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача группы по проекту',
                'verbose_name_plural': 'Задача группы по проекту',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('В работу', 'В работу'), ('Выполняется', 'Выполняется'), ('Выполнена', 'Выполнена'), ('Ожидает ОС', 'Ожидает ОС'), ('На правках', 'На правках'), ('Завершена', 'Завершена'), ('На паузе', 'На паузе')], max_length=50, verbose_name='Статус')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.taskgroup', verbose_name='Задача группы')),
            ],
            options={
                'verbose_name': 'Статус задачи группы',
                'verbose_name_plural': 'Статус задачи группы',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('В работу', 'В работу'), ('Выполняется', 'Выполняется'), ('Выполнена', 'Выполнена'), ('Ожидает ОС', 'Ожидает ОС'), ('На правках', 'На правках'), ('Завершена', 'Завершена'), ('На паузе', 'На паузе')], max_length=50, verbose_name='Статус')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.taskgroup', verbose_name='Задача студента')),
            ],
            options={
                'verbose_name': 'Статус задачи студента',
                'verbose_name_plural': 'Статус задачи студента',
            },
        ),
        migrations.CreateModel(
            name='TaskStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('project_cost', models.CharField(max_length=120, verbose_name='Стоимость')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.project', verbose_name='Проект')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Задача студента по проекту',
                'verbose_name_plural': 'Задача студента по проекту',
            },
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='account.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Капитан группы'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='админ'),
        ),
    ]
