# Generated by Django 4.2.3 on 2023-08-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_answertesttask_options_answergroup_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Разделы',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='UnderSectionFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Под раздел')),
            ],
            options={
                'verbose_name': 'Раздел Образование',
                'verbose_name_plural': 'Раздел Образование',
            },
        ),
        migrations.AlterModelOptions(
            name='dataknowledge',
            options={'verbose_name': 'База знаний платно', 'verbose_name_plural': 'База знаний платно'},
        ),
        migrations.CreateModel(
            name='DataKnowledgeFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Тема')),
                ('url', models.TextField(verbose_name='Ссылки')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.chapterfree', verbose_name='Раздел')),
                ('under_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.undersectionfree', verbose_name='Под раздел')),
            ],
            options={
                'verbose_name': 'База знаний бесплатно',
                'verbose_name_plural': 'База знаний бесплатно',
            },
        ),
    ]
