# Generated by Django 4.2.3 on 2023-08-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_chapterfree_undersectionfree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataknowledgefree',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.chapter', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='dataknowledgefree',
            name='under_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.undersection', verbose_name='Под раздел'),
        ),
        migrations.DeleteModel(
            name='ChapterFree',
        ),
        migrations.DeleteModel(
            name='UnderSectionFree',
        ),
    ]
