# Generated by Django 4.2.3 on 2023-08-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_comment_groupstudent_project_studentcv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcv',
            options={'verbose_name': 'Резюме студента', 'verbose_name_plural': 'Резюме студента'},
        ),
        migrations.AlterModelOptions(
            name='studentportfolio',
            options={'verbose_name': 'Портфолио студента', 'verbose_name_plural': 'Портфолио студента'},
        ),
    ]
