# Generated by Django 4.2.3 on 2023-08-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_dataknowledgefree_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain_group_students', to='account.student'),
        ),
    ]
