# Generated by Django 4.2.3 on 2023-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_taskstatusstudent_task_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterestsFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=150, verbose_name='Интерес')),
            ],
            options={
                'verbose_name': 'Профессиональная сфера интересов',
                'verbose_name_plural': 'Профессиональная сфера интересов',
            },
        ),
        migrations.CreateModel(
            name='UserInterestsSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=150, verbose_name='Интерес')),
            ],
            options={
                'verbose_name': 'Интересующие Вас ниши',
                'verbose_name_plural': 'Интересующие Вас ниши',
            },
        ),
        migrations.CreateModel(
            name='UserInterestsThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=150, verbose_name='Интерес')),
            ],
            options={
                'verbose_name': 'Цели',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='other_interest_first',
            field=models.CharField(default=1, max_length=150, verbose_name='Профессиональная сфера интересов другое'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='other_interest_second',
            field=models.CharField(default=1, max_length=150, verbose_name='Интересующие Вас ниши другое'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='other_interest_third',
            field=models.CharField(default=1, max_length=150, verbose_name='цели другие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='interest_first',
            field=models.ManyToManyField(to='account.userinterestsfirst', verbose_name='Профессиональная сфера интересов'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_second',
            field=models.ManyToManyField(to='account.userinterestssecond', verbose_name='Интересующие Вас ниши'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_third',
            field=models.ManyToManyField(to='account.userintereststhird', verbose_name='Цели'),
        ),
    ]
