# Generated by Django 4.2.3 on 2023-08-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userinterestsfirst_userinterestssecond_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest_first',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest_second',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest_third',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_interest_first',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_interest_second',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_interest_third',
        ),
        migrations.AddField(
            model_name='student',
            name='interest_first',
            field=models.ManyToManyField(to='account.userinterestsfirst', verbose_name='Профессиональная сфера интересов'),
        ),
        migrations.AddField(
            model_name='student',
            name='interest_second',
            field=models.ManyToManyField(to='account.userinterestssecond', verbose_name='Интересующие Вас ниши'),
        ),
        migrations.AddField(
            model_name='student',
            name='interest_third',
            field=models.ManyToManyField(to='account.userintereststhird', verbose_name='Цели'),
        ),
        migrations.AddField(
            model_name='student',
            name='other_interest_first',
            field=models.CharField(default=1, max_length=150, verbose_name='Профессиональная сфера интересов другое'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='other_interest_second',
            field=models.CharField(default=1, max_length=150, verbose_name='Интересующие Вас ниши другое'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='other_interest_third',
            field=models.CharField(default=1, max_length=150, verbose_name='цели другие'),
            preserve_default=False,
        ),
    ]
