# Generated by Django 4.2.3 on 2023-08-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_interest_first_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименования')),
            ],
            options={
                'verbose_name': 'Образования',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименования')),
            ],
            options={
                'verbose_name': 'ВУЗ',
                'verbose_name_plural': 'ВУЗ',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=120, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest_first',
            field=models.ManyToManyField(blank=True, null=True, to='account.userinterestsfirst', verbose_name='Профессиональная сфера интересов'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest_second',
            field=models.ManyToManyField(blank=True, null=True, to='account.userinterestssecond', verbose_name='Интересующие Вас ниши'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest_third',
            field=models.ManyToManyField(blank=True, null=True, to='account.userintereststhird', verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_interest_first',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Профессиональная сфера интересов другое'),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_interest_second',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Интересующие Вас ниши другое'),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_interest_third',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='цели другие'),
        ),
        migrations.AddField(
            model_name='student',
            name='before_university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.beforeuniversity', verbose_name='Образования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.university', verbose_name='ВУЗ'),
        ),
    ]
