# Generated by Django 4.2.3 on 2023-08-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_beforeuniversity_university_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interest_first',
            field=models.ManyToManyField(blank=True, to='account.userinterestsfirst', verbose_name='Профессиональная сфера интересов'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest_second',
            field=models.ManyToManyField(blank=True, to='account.userinterestssecond', verbose_name='Интересующие Вас ниши'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest_third',
            field=models.ManyToManyField(blank=True, to='account.userintereststhird', verbose_name='Цели'),
        ),
    ]
