# Generated by Django 4.2.3 on 2023-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('previous_flow', 'Прошлый поток'), ('subscribed_to_chatbot', 'Подписан на чат-бот'), ('lead', 'Лид'), ('in_progress', 'В работе у менеджера'), ('rejected', 'Отказ'), ('awaiting_payment', 'Ожидает оплаты'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен'), ('graduate', 'Выпускник'), ('working_group', 'Рабочая группа'), ('dropout', 'Выбыл')], max_length=30, null=True, verbose_name='Статус'),
        ),
    ]
