# Generated by Django 4.2.3 on 2023-08-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='оценка'),
        ),
    ]
