# Generated by Django 4.2.3 on 2023-08-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_course_alter_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstudent',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='оценка'),
        ),
    ]
