# Generated by Django 4.2.3 on 2023-08-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_taskstudent_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Разделы',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='UnderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Под раздел')),
            ],
            options={
                'verbose_name': 'Под раздел',
                'verbose_name_plural': 'Под раздел',
            },
        ),
        migrations.CreateModel(
            name='DataKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Тема')),
                ('url', models.TextField(verbose_name='Ссылки')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.chapter', verbose_name='Раздел')),
                ('under_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.undersection', verbose_name='Под раздел')),
            ],
            options={
                'verbose_name': 'База знаний',
                'verbose_name_plural': 'База знаний',
            },
        ),
    ]
