# Generated by Django 4.2.3 on 2023-08-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_chapter_undersection_dataknowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='education_status',
            field=models.CharField(choices=[('free_subscription_registration', 'Регистрация на бесплатную подписку'), ('completed_free_subscription', 'Завершена бесплатная подписка'), ('paid_subscription_member', 'Участник платной подписки'), ('course_participant', 'Участник курса'), ('dropped_out', 'Выбыл'), ('completed_education', 'Завершил обучение')], default=1, max_length=30, verbose_name='Статус обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mailing_status',
            field=models.CharField(choices=[('delivered', 'Доставлено'), ('viewed', 'Просмотрено'), ('opened', 'Открыто')], default=1, max_length=20, verbose_name='Статус рассылки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='manager_status',
            field=models.CharField(choices=[('lead', 'Лид'), ('in_progress', 'В работе у менеджера'), ('rejected', 'Отказ'), ('waiting_for_payment', 'Ожидает оплаты'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен')], default=1, max_length=20, verbose_name='Статус менеджера'),
            preserve_default=False,
        ),
    ]
