# Generated by Django 4.2.3 on 2023-08-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_student_status_student_education_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mailing_status',
        ),
    ]
