# Generated by Django 4.2.3 on 2023-08-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_student_mailing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatusstudent',
            old_name='task_group',
            new_name='task_student',
        ),
    ]
